#!/bin/bash

CURDIR="`readlink -f $0`"; CURDIR="${CURDIR%/*}"
docker run --rm -u `id -u`:`id -g` --name reg-api-server-initdb `bash $CURDIR/mountfolders_docker` -it --entrypoint /usr/local/bin/python3 reg-api:latest /home/reg-api/bin/reg-api initdb
